In [49]:
from skimage.color import rgb2gray, rgb2hsv
from matplotlib.pyplot import bar
from skimage.exposure import histogram
from skimage.util import random_noise
import numpy as np
import matplotlib.pyplot as plt
import skimage.io as io
from skimage.filters import median
from skimage.filters import gaussian
from skimage.color import rgb2gray,rgb2hsv
# import the opencv library
import cv2
#new
from scipy import ndimage
from datetime import datetime
import numpy as np
import math

# Show the figures / plots inside the notebook
%matplotlib inline

import cv2 
import numpy as np
import math
import skimage.io as io


In [50]:

def show_images(images, titles=None):
    n_ims = len(images)
    if titles is None:
        titles = ['(%d)' % i for i in range(1, n_ims + 1)]
    fig = plt.figure()
    n = 1
    for image, title in zip(images, titles):
        a = fig.add_subplot(1, n_ims, n)
        if image.ndim == 2:
            plt.gray()
        plt.imshow(image)
        a.set_title(title)
        n += 1
    fig.set_size_inches(np.array(fig.get_size_inches()) * n_ims)
    plt.show()


In [51]:
def enhancement(crop_image):
     # Apply Gaussian blur
    blur = cv2.GaussianBlur(crop_image, (3,3), 0)
    
    # Change color-space from BGR -> HSV
    hsv = cv2.cvtColor(blur, cv2.COLOR_BGR2HSV)
    
    # Create a binary image with where white will be skin colors and rest is black
    mask2 = cv2.inRange(hsv, np.array([0,0,0]), np.array([20,255,255]))
    
    # Kernel for morphological transformation    
    kernel = np.ones((5,5))
    
    # Apply morphological transformations to filter out the background noise
    dilation = cv2.dilate(mask2, kernel, iterations = 1)
    erosion = cv2.erode(dilation, kernel, iterations = 1)    
       
    # Apply Gaussian Blur and Threshold
    mask = cv2.GaussianBlur(erosion, (3,3), 0)
    return mask     

In [52]:


#set initial values
flag = {"first": False, "operator": False, "second": False}
count_same_frames = 0
first, operator, second = "", "", ""
pred_text = ""
calc_text = ""
info = "Enter first number"        

# define a video capture object
vid = cv2.VideoCapture(0)

while (True):

    ret, frame = vid.read()
    dim = (1000, 800)
    frame = cv2.resize(frame, dim, interpolation = cv2.INTER_AREA)
    # Display the resulting frame
    frame = cv2.flip(frame, 1)
    # Get hand data from the rectangle sub window   
    cv2.rectangle(frame,(500,400),(990,790),(0, 0, 0),2)
    crop_image = frame[ 400:790,500:990]
    
    mask=enhancement(crop_image)
    
    
    

    try:
        ret, thresh = cv2.threshold(mask, 127, 255,0)
        contours, hierarchy = cv2.findContours(thresh,2,1)
        #new added 
        old_pred_text = pred_text
        if len(contours)!=0:
            #find contour of max area(hand)
            cnt = max(contours, key = lambda x: cv2.contourArea(x))
            # print(max(contours, key = lambda x: cv2.contourArea(x)))


            #approx the contour a little
            epsilon = 0.0005*cv2.arcLength(cnt,True)
            approx= cv2.approxPolyDP(cnt,epsilon,True)
            
            #make convex hull around hand
            hull = cv2.convexHull(cnt)
            print(cnt)
            #define area of hull and area of hand
            areahull = cv2.contourArea(hull)
            areacnt = cv2.contourArea(cnt)

        #find the percentage of area not covered by hand in convex hull
            if areacnt!=0:
                arearatio=((areahull-areacnt)/areacnt)*100
            else :
                arearatio=0    
            #find the defects in convex hull with respect to hand
            hull = cv2.convexHull(approx, returnPoints=False)
            if len(hull)!=0:
                print('hull')
                print(hull)
                defects = cv2.convexityDefects(approx, hull)
               
                l=1   
          

                    #code for finding no. of defects due to fingers
                for i in range(defects.shape[0]):
                        s,e,f,d = defects[i,0]
                        start = tuple(approx[s][0])
                        end = tuple(approx[e][0])
                        far = tuple(approx[f][0])
                        pt= (100,180)


                        # find length of all sides of triangle
                        a = math.sqrt((end[0] - start[0])**2 + (end[1] - start[1])**2)
                        b = math.sqrt((far[0] - start[0])**2 + (far[1] - start[1])**2)
                        c = math.sqrt((end[0] - far[0])**2 + (end[1] - far[1])**2)
                        

                        

                        # apply cosine rule here
                        angle = (math.acos((b ** 2 + c ** 2 - a ** 2) / (2 * b * c)) * 180) / 3.14
                        print(angle)        

                        
                        if angle <= 80:
                           l += 1
                           cv2.circle(crop_image,far,5,[255,255,255],-1)

                        
                        if(angle>=90 and angle <130):
                           sign='+'

                        if(angle>=150 and angle <=180):
                           sign='-'   

                        #draw lines around hand
                        cv2.line(crop_image,start, end, [0,255,0], 2)
                        
                        cv2.circle(crop_image, start, 4, [255,0,0], -1)
                        cv2.circle(crop_image, end, 4, [0,0,255], -1)#[0,0,255]:red
                        cv2.circle(crop_image, far, 3, [0,255,0], -1)
               


    
               
                font = cv2.FONT_HERSHEY_SIMPLEX
                
                pred_text = l
                if old_pred_text == pred_text:
                        count_same_frames += 1
                else:
                        count_same_frames = 0
                
                if count_same_frames > 30 :
                    # count_same_frames = 0
                    # first, second, operator, pred_text, calc_text = '', '', '', '', ''
                    # flag['first'], flag['operator'], flag['second'], flag['clear'] = False, False, False, False
                    # info = "Enter first number"
                    if  flag['first'] == False and flag['operator'] == False and flag['second'] == False :
                         count_same_frames = 0
                         first, second, operator, pred_text, calc_text = pred_text, '', '', '', ''
                         info = "Enter the Sign"
                         flag['first'] = True 
                         flag['operator'] = False 
                         flag['second'] = False
                    elif flag['first'] == True and flag['operator'] == False and flag['second'] == False :
                         count_same_frames = 0
                         #operator will be changed later
                         second, operator, pred_text, calc_text = '', pred_text, '', ''
                         info = "Enter the second operand"
                         flag['first'] = True 
                         flag['operator'] = True  
                         flag['second'] = False
                    elif flag['first'] == True and flag['operator'] == True and flag['second'] == False :
                         count_same_frames = 0
                         second, pred_text, calc_text = pred_text,'', ''
                         if(sign=='+'):
                          result=first+ second
                         elif(sign=='-'):
                            result=first- second



                         print(result)
                         info=str(first)+sign+str(second)
                         info += '='+ str(result)  
                         flag['first'] = True 
                         flag['operator'] = True  
                         flag['second'] =  True  
                print(l)
                cv2.putText(frame, info, (30, 440), cv2.FONT_HERSHEY_TRIPLEX, 1, (0, 255, 255) )
                if l==1:
                    cv2.putText(frame,'1',(0,50), font, 2, (0,0,255), 3, cv2.LINE_AA)

                elif l==2:
                    cv2.putText(frame,'2',(0,50), font, 2, (0,0,255), 3, cv2.LINE_AA)

                elif l==3:
                    cv2.putText(frame,'3',(0,50), font, 2, (0,0,255), 3, cv2.LINE_AA)
                elif l==4:
                    cv2.putText(frame,'4',(0,50), font, 2, (0,0,255), 3, cv2.LINE_AA)

                elif l==5:
                    cv2.putText(frame,'5',(0,50), font, 2, (0,0,255), 3, cv2.LINE_AA)
                elif l==6:
                    cv2.putText(frame,'6',(0,50), font, 2, (0,0,255), 3, cv2.LINE_AA)   
                elif l==7:
                    cv2.putText(frame,'7',(0,50), font, 2, (0,0,255), 3, cv2.LINE_AA)     
                elif l==8:
                    cv2.putText(frame,'8',(0,50), font, 2, (0,0,255), 3, cv2.LINE_AA)
                elif l==9:
                    cv2.putText(frame,'9',(0,50), font, 2, (0,0,255), 3, cv2.LINE_AA)  
                elif l==10:
                    cv2.putText(frame,'10',(0,50), font, 2, (0,0,255), 3, cv2.LINE_AA)          

                else :
                    cv2.putText(frame,'reposition',(10,50), font, 2, (0,0,255), 3, cv2.LINE_AA)


       
        cv2.imshow('frame',frame)        
        cv2.imshow('mask',mask)  

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break 

        
    except:
        print('error and skip')
# After the loop release the cap object
vid.release()
# Destroy all the windows
cv2.destroyAllWindows()


[[[ 22 374]]

 [[ 21 375]]

 [[ 21 376]]

 [[ 21 377]]

 [[ 22 377]]

 [[ 23 376]]

 [[ 23 375]]]
hull
[[5]
 [4]
 [3]
 [2]
 [1]
 [0]]
error and skip
[[[0 0]]

 [[0 1]]

 [[0 2]]

 ...

 [[3 0]]

 [[2 0]]

 [[1 0]]]
hull
[[8]
 [7]
 [0]]
90.34037596823823
1
[[[0 0]]

 [[0 1]]

 [[0 2]]

 ...

 [[3 0]]

 [[2 0]]

 [[1 0]]]
hull
[[9]
 [8]
 [0]]
90.34037596823823
1
[[[ 20 361]]

 [[ 20 362]]

 [[ 20 363]]

 [[ 20 364]]

 [[ 21 364]]

 [[ 22 364]]

 [[ 23 363]]

 [[ 23 362]]

 [[ 22 361]]

 [[ 21 361]]]
hull
[[5]
 [4]
 [3]
 [2]
 [1]
 [0]]
error and skip
[[[0 0]]

 [[0 1]]

 [[0 2]]

 ...

 [[3 0]]

 [[2 0]]

 [[1 0]]]
hull
[[8]
 [7]
 [0]]
90.19301361131117
1
[[[0 0]]

 [[0 1]]

 [[0 2]]

 ...

 [[3 0]]

 [[2 0]]

 [[1 0]]]
hull
[[4]
 [3]
 [0]]
90.34037596823823
1
[[[ 21 373]]

 [[ 20 374]]

 [[ 19 374]]

 [[ 19 375]]

 [[ 19 376]]

 [[ 20 376]]

 [[ 21 376]]

 [[ 22 376]]

 [[ 23 375]]

 [[ 23 374]]

 [[ 22 373]]]
hull
[[7]
 [6]
 [5]
 [4]
 [2]
 [1]
 [0]]
135.06847396007075
1
[[[ 21 373]]

 [